### ISSUE TITLE
Transaction-ID of contribution should be populated

### ISSUE THREAD

**Issue by Detsieber** [Project60/sepa_dd#106]
Transaction-ID should be filled with:

{PmtInfId} EREF:{contribution.ID}"

This allows the user to search contributions by the end to end reference, as well as seeing all contributions within a specific pain file.

Writing this info to the contributions should happen ~~when the pain file is created~~ (see #94) at the same moment when the contribution is marked as "completed".

**Comment by systopia** [comment]
In the improved payment processor we use the ``trxn_id``.

@Detsieber: Is that enough for your scenario or do you need it to be populated always? What's your scenario?

**Comment by Detsieber** [comment]
I believe this will be enough! No further work should be done on that (in reality, we never had the need to do any search based on the transaction id).

**Comment by systopia** [comment]
Thanks for your feedback @Detsieber, I'll close the ticket then.
