### ISSUE TITLE
PDF prenotification file is empty

### ISSUE THREAD

**Issue by nikobo** [Project60/sepa_dd#161]
When I create a PDF prenotification file for the first time an empty file is returned. After that the correct one is created using the Wikimedia France template.

**Comment by nikobo** [comment]
It seems  that this issue has changed a little bit. It no longer creates an empty pdf file at the first try, but in CiviCRM 4.5+ the prenotification button does not work. It fails with the following error message:

>Network Error
>Unable to reach the server. Please refresh this page in your browser and try again.

**Comment by nikobo** [comment]
I'm closing this issue because it no longer exists in the form described in my first post.

**Comment by systopia** [comment]
For the record: fixed as side effect of https://github.com/Project60/sepa_dd/issues/239
