### ISSUE TITLE
make the SEPA Creditor identifier more visible

### ISSUE THREAD

**Issue by tttp** [Project60/sepa_dd#179]
We should probably add a more visible link to edit the creditor identifier. Is there already a link to create a new one/edit the existing one I missed?

we should IMO as well display the creditor on the mandate page /civicrm/sepa/xmandate

**Comment by systopia** [comment]
> what about not displaying the creditor on the mandate page? It might be that I just skipped it when I wrote that code. Do you see a reason not to display it?

If you mean by that, that we *should* do it, than it's just been implemented with https://github.com/Project60/sepa_dd/issues/194
