### ISSUE TITLE
New "SEPA Dashboard" menu appears misplaced

### ISSUE THREAD

**Issue by elcapo** [Project60/sepa_dd#195]
When installing the extension, the new SEPA Dashboard menu, sometimes, appears misplaced, as shown in the attached image:

![screenshot from 2014-09-29 23 44 03](https://cloud.githubusercontent.com/assets/1746692/4450834/96b4ca32-482a-11e4-905f-7fe6b2c845eb.png)

The error has been reproduced using:
* CiviCRM version: **4.5.1**
* CMS: **Drupal**

**Comment by systopia** [comment]
fix now in master and released in 1.0.1rc1
