### ISSUE TITLE
EVENT: Mandatory key(s) missing from params array: contact_id

### ISSUE THREAD

**Issue by magnolia61** [Project60/sepa_dd#208]
When registering for an event I get the following after the confirmation screen
Mandatory key(s) missing from params array: contact_id

What is most probable at fault here? The fact that I use 4.5.3 of my Joomla install?

**Comment by magnolia61** [comment]
Unfortunately $params['contact_id'] = $params['contactID']; didn't work for me
I still get a white screen and the error_reporting extension mailing me on:
Mandatory key(s) missing from params array: contact_id

I have tried with &smartyDebug=1 but couldn't figure out why your supposed code would not work.
The drupal recent error log gives two notices:

Notice: Undefined index: contributionType_name in CRM_Core_Payment_SDD->doDirectPayment() (line 131 of /home/ozk/domains/ourdomain.nl/public_html/crm/sites/all/modules/civicrm_extensions/sepa_dd/CRM/Core/Payment/SDD.php).
AND
Notice: Undefined variable: contact_id in CRM_Core_Payment_SDD->doDirectPayment() (line 141 of /home/ozk/domains/onvergetelijk.nl/public_html/crm/sites/all/modules/civicrm_extensions/sepa_dd/CRM/Core/Payment/SDD.php).

I guess not only the fact is to blame that I'm trying to use an event registration form, because using a standard contribution page I can only make recurring payments and not One Offs.

Does this help? I'd love to do some more debugging or try out possible solutions to get one-off event registrations working ;) Any idea's?

**Comment by systopia** [comment]
@magnolia61 I assume this is still an event registration page, correct? And is it the "bleeding" dev_pp code?

**Comment by magnolia61** [comment]
Semi-good news! After todays commits I can register for an event without fatal errors. The hidden start date is no blocker and the contact_id get's set.

Two things do not work well so far though:
1) The mandate does'nt show up after generating from the dashboard (it get's recorded in the DB correctly though)
2) The recorded contribution get's incorrectly set as 'paid by: creditcard' (instead of SEPA OOFF)
3) The credit card mentions are still in the confirmation page (and confirmation mail)
     Instead it would be better to show and email the Bank # and BIC code of the mandate.

I hope my testing & feedback helps to get the event registration SEPA OOFF's working  :-) 
I am better in testing and proposing than actual coding, so thanks a lot for your work on this!

**Comment by magnolia61** [comment]
I uploaded the current integrated master files and got the following results:
1) Notice in 1st screen: org.project60.sepa: get_parameter for unknown key: cycledays, referer: https://www.ourdomain.nl/civicrm/event/register?reset=1&id=29
2) (Fatal error) /home/ozk/domains/ourdomain.nl/public_html/crm/sites/all/modules/civicrm/CRM/Event/BAO/Event.php(1699): CRM_Core_Error::fatal("Cannot find participant ID")

Later today we could go on skype to discuss a little easier. I am glad to help getting the event part functioning.

**Comment by nikobo** [comment]
Just a quick notice regarding this php message:
>org.project60.sepa: get_parameter for unknown key: cycledays

This can happen if the extension has not been uninstalled before updating to the latest master files.

**Comment by systopia** [comment]
> This can happen if the extension has not been uninstalled before updating to the latest master files.

Of course. The process for updating from any source is:
 1. deactivate and uninstall extension
 2. update code
 3. install / activate extension

Otherwise all (new) changes that need to be done upon install will not be applied.

**Comment by magnolia61** [comment]
After a full uninstall and clean install of the current master code the following issues remain:

1) The mandate get's recorded in civicrm_sdd_mandate with status PARTIAL, entity_id=4294967295 and with contact_id = NULL (which prevents it fro showing up in the mandate dashboard of course)
2) The recorded contribution get's incorrectly set as 'paid by: creditcard' (instead of SEPA OOFF) and with status 'complete' (instead of 'Pending')

So somehow with the new mandate creation method, the event registration mandates get only initially set but do not get finished. Some observations:
a) an event registration gets recorded correctly (status: registered)
b) a contribution gets recorded almost correctly
c) a mandate gets recorded only partially

What can I do to help debug this further and help test to get the event registration part working?

**Comment by systopia** [comment]
That makes perfect sense to me. After the payment processor has finisehd, ``CRM_Core_Payment_SDD::processPartialMandates()`` needs to be called to hook the payments up with their respective mandates. This call seems to be missing in your case. I'll take care of this.

**Comment by magnolia61** [comment]
Maybe of interest for you, Björn. But after the situation in the screenshot I did a regular test-contribution again and the two event based mandates changed their mandate status by that action from partial to OOFF. The only thing that is not filled is the contact_id.
So two observations:
1)  You seem to be right that triggering CRM_Core_Payment_SDD::processPartialMandates() from the regular contribution screen was somewhat helpfull for the event mandates
2) The contact_id probably still needs to be set initialy, because this is still not filled.
Does this sound like progress? I love that sound!
![sepadd_database_mandates afterdonation](https://cloud.githubusercontent.com/assets/2195908/5713451/c15d58aa-9abc-11e4-9237-0634e886ec46.png)

**Comment by systopia** [comment]
@magnolia61 Making the payment processor work for event registration pages is work in progress - we're actually on this right now. I'll ask you to test this again soon.

**Comment by systopia** [comment]
@magnolia61: I have now modified/extended the payment processor to work with event registrations. Could you please test with the current ``master``?

**Comment by magnolia61** [comment]
Event registrations now work out of the box! Congratulations! The only issue right now are:
1) the missing mandate summary in confirmation email
2) the reduntant CC+billing block) in the confirmation email
But these already have their issue in: https://github.com/Project60/sepa_dd/issues/217

The coming days we start with live transactions. I will get back to you with bugs, observations & suggestions :-) Thanks for making this happen!

**Comment by systopia** [comment]
Thanks for testing. I moved the email issue to https://github.com/Project60/sepa_dd/issues/237
