### ISSUE TITLE
Integrate "Little BIC extension"

### ISSUE THREAD

**Issue by systopia** [Project60/sepa_dd#211]
Use the data provided by the "Little BIC extension" (https://github.com/Project60/org.project60.bic) -if installed- to automatically fill the BIC form fields when the IBAN was entered.

**Comment by magnolia61** [comment]
Does this relate to menu injection errors in 4.5? [in: org.project60.bic/bic.php]
Undefined variable: new_nav_id in bic_civicrm_navigationMenu()
Notice: Undefined index: attributes in CRM_Utils_SepaMenuTools::getMaxNavID() 
[in: sepa_dd/CRM/Utils/SepaMenuTools.php]

**Comment by systopia** [comment]
> Does this relate to menu injection errors in 4.5?

Most likely: no.

**Comment by systopia** [comment]
Integration should now work in ``master``. You will have to update the BIC extension to a current version. If you want it to work on payment processors you will also have to give anonymous users the ``access AJAX API`` permission.

@magnolia61: Could you please test and report?

**Comment by magnolia61** [comment]
Most of the time it works now, but a little slow for user experience, so I would got to a next field, return and have it not filled in anyway. Would it be difficult to put a little ajax-style button next to the BIC field to also retrieve the BIC by pushing it? (so the UX is never broken and the solution is fool-proof)

**Comment by systopia** [comment]
@magnolia61 Can't we do both? On our servers it's reasonably fast, and I wouldn't want everyone having to press an extra button. 

But in any case, I could add a little 'busy' indicator so people know it's being checked/processed.

**Comment by magnolia61** [comment]
Both would be nice and fool-proof. It's working now with us if I wait a little. The small syncbutton and busy indicator would leave people without questions. NIce idea, the icon!

**Comment by systopia** [comment]
@magnolia61: I just added the busy indicator. I also added the extra button, but then I disabled (hid) it again, because it just seems confusing. Have a look and tell me what you think...

**Comment by magnolia61** [comment]
Hi Bjorn, the busyicon works ok enough I think. There are some small glitches though.
1) If you tab back from BIC to IBAN and change part of the IBAN only the help text of the BIC get's updated
2) I do not know how the IBAN validation works but maybe the BIC should not load in case of an invalid IBAN number. This might be confusing.
3) It would be great to show in the same way a busy-icon and maybe green-check for entering a valid (of red cros for invalid) IBAN number

**Comment by systopia** [comment]
> If you tab back from BIC to IBAN and change part of the IBAN only the help text of the BIC get's updated

If by that you mean, that the BIC field does not get deleted, that's on purpose. We didn't want to the user's input - and the system doesn't keep track of whether it was the lookup or the user who entered it in the first place. @magnolia61 How would you expect it to react?

I moved 2) and 3) to #238

**Comment by systopia** [comment]
Ok, this generally seems to work. We'll take care of #238 when there's funding for it
