### ISSUE TITLE
EVENT: Cosmetic issue: Credit Card info on event confirmation page

### ISSUE THREAD

**Issue by magnolia61** [Project60/sepa_dd#217]
I know it is just a cosmetic issue, but on the event confirmation page a line with Credit Card information shows, even when no CC PP at all is used. This might confuse some participants. It's probably an easy fix.

![sepadd_master_confirmpage_ccinfo](https://cloud.githubusercontent.com/assets/2195908/5531181/056ebeb6-8a29-11e4-9026-9749ef28f545.png)

**Comment by magnolia61** [comment]
I doublechecked qwith the current master on a completely different website and it only happens when sepa_dd is enabled. The credit card information (and empty billing info) also pops up in the confirmation email btw.

![sepadd_creditcard_info_email](https://cloud.githubusercontent.com/assets/2195908/5699965/8a4d5492-9a34-11e4-95c4-9462cb2b11a2.png)

**Comment by systopia** [comment]
@nikobo Could you have a look at this?

**Comment by magnolia61** [comment]
The credit card information (and empty billing info) is redundant and needs to be removed from the  event registration pages. On the other hand there some vital info sepamandate info is missing from
1) confirmation screen
2) thank-you screen and 
3) email confirmation
When registering through a  'regular' contribution form the users' Bank account information and the mandate summary is (I must say brilliantly) displayed on screen.

In all cases the mandate-summary is missing from the email confirmation). For Dutch (and I guess also German and some users from some other EU countries) this is especially important as the thankyou screen and confirmation email are in fact the legal mandate that has just been given.

So, as well as removing the redundant creditcard (and empty billing info), the missing mandate info is also welcome to make it's way towards the event registration pages and confirmation email :-)

![sepadd_donation_confirmation-screen_crop](https://cloud.githubusercontent.com/assets/2195908/5717914/e50fd21e-9b07-11e4-852c-eff056244c49.png)
![sepadd_donation_thankyou-screen_crop](https://cloud.githubusercontent.com/assets/2195908/5717913/e4152152-9b07-11e4-9fe8-d2a6ff3ac4ca.png)

**Comment by tttp** [comment]
Trying to remember how I avoided it in the first version of the PP for
sepa.

@systopia, it was a mode/flag to set somewhere, but that created other
problems elsewhere that I had to work around.

I'll ping you and we have a conf to check out how to solve.

**Comment by magnolia61** [comment]
Would you advise me to split this issue in two seperate ones?
1) issue #1 remove credit card info on screens and in confirmation email
2) issue #2 include mandate summary info block in confirmation email

**Comment by systopia** [comment]
@magnolia61 Making the payment processor work for event registration pages is work in progress - we're actually on this right now. I'll ask you to test this again soon.

**Comment by systopia** [comment]
@magnolia61: I have now modified/extended the payment processor to work with event registrations. Could you please test with the current ``master``?

**Comment by magnolia61** [comment]
Thanks Bjorn for making the event registrations work. Your 'hack' to replace the credit card info on the confirmation and thank you screen works nice and registrations pass throught correctly now!
The credit card and billing info still appears in the confirmation email though. Probably that has to do with civicrm not realy understanding the type of payment processor civisepa actually is.

Both the billing block in the email, as well as the creditcard information have the following conditionals:
{if $contributeMode eq 'direct' and !$isAmountzero and !$is_pay_later and !$isOnWaitlist and !$isRequireApproval}

Would you think it would be possible to get the mandate summary information in the confirmation email and remove the billing & creditcard info? (without changing core?)

**Comment by systopia** [comment]
@magnolia61 Since the original problem of this ticket seems resolved, I moved this last topic to https://github.com/Project60/sepa_dd/issues/237. Also, please note that I have currently no funding for the whole event registration, so I cannot spend arbitrary amounts of hours on it.
