### ISSUE TITLE
Creditor custom setting cannot be stored?

### ISSUE THREAD

**Issue by magnolia61** [Project60/sepa_dd#230]
Am I wrong or are the custom creditor notice and horizon day setting still only placeholders?
Some observations:
1) The creditor tag and creditor mandate prefix are not yet configurable (only directly in the DB)
2) The cycle days doesn;t even show a default.
If the settings are stil work-in-progress I can understand, otherwise, please let me know

**Comment by systopia** [comment]
> Am I wrong or are the custom creditor notice and horizon day setting still only placeholders?

What do you mean by "custom creditor notice"?

> The creditor tag and creditor mandate prefix are not yet configurable (only directly in the DB)

That's correct. If you need it, please open a separate ticket.

> The cycle days doesn;t even show a default.

That's not correct. But: the cycle days default value is empty. If you read the help bubble you'll find that that means "any day". If you set another default value, this value is shown when editing particular creditors just the same.

**Comment by magnolia61** [comment]
Whatever I do the Custom Batching settings do nog get saved. Should they go in the  civicrm_sdd_creditor table? Because I do not see fields over there to hold the settings. Maybe the sql is missing some fields?
![Uploading Sepa_DD_CustomBatchingSettings.png . . .]()
![sepa_dd_creditorfields](https://cloud.githubusercontent.com/assets/2195908/5737523/2b90b8d6-9be2-11e4-9304-ffd9838e9e06.png)

**Comment by systopia** [comment]
> Because I do not see fields over there to hold the settings. Maybe the sql is missing some fields?

No, they are stored using the CiviCRM settings system. On my end that all works well. Are you sure you sure you're doing the deinstall-reinstal cycle with every update? This error would be a typical symptom of it.

**Comment by nikobo** [comment]
There is still a bug with an empty default cycle days setting, which i'm currently working on. I'll keep you updated.

**Comment by systopia** [comment]
@nikobo Is this fixed now?

**Comment by nikobo** [comment]
Yes it is fixed. A non-empty value for 'cycle days' should no longer override the individual creditor 'cycle days'-setting.
