### ISSUE TITLE
InvalidDatatypeValueException for <MsgId> and <PmtInfId>

### ISSUE THREAD

**Issue by Detsieber** [Project60/sepa_dd#244]
If more than one xml file of the same group type is created on the same day, the values for file name, MsgId and PmtInfId are counted up by one, preceded by a "_".

Example:

First file: "SDDXML-TXG-1-FRST-2015-02-10"
Second file: "SDDXML-TXG-1-FRST-2015-02-10_1"

However, the "_" is a prohibited character here. Files are rejected, and the "SEPA XML Checker" gives the following error message:

Datatype error: Type:InvalidDatatypeValueException, Message:Value 'SDDXML-TXG-1-FRST-2015-02-10_1' does not match regular expression facet '([A-Za-z0-9]|[\+|\?|/|\-|:|\(|\)|\.|,|'| ]){1,35}'.
Datatype error: Type:InvalidDatatypeValueException, Message:Value 'TXG-1-FRST-2015-02-10_1' does not match regular expression facet '([A-Za-z0-9]|[\+|\?|/|\-|:|\(|\)|\.|,|'| ]){1,35}'.

While some banks might tolerate this violation, at least the Bank für Sozialwirtschaft doesn't accept SEPA xml files like this.

As a workaround, files can be patched. However, for a stable version of SEPA DD, this should be changed: e.g., use a hyphen ("-") instead of the underscore.

**Comment by systopia** [comment]
Should have been fixed a long time ago: https://github.com/Project60/sepa_dd/commit/93ba8f5fc1a20588531a47c112b2dad1d2510a35
@Detsieber  Which version are you using?

**Comment by systopia** [comment]
@Detsieber  You are absolutely right, fix https://github.com/Project60/sepa_dd/commit/93ba8f5fc1a20588531a47c112b2dad1d2510a35 didn't fix this. 
I'll release a new 1.0.1rc soon.

**Comment by systopia** [comment]
Fortunately, it was an easy fix.
@Detsieber: could you please test this again with [org.project60.sepa-1.0.1rc2](https://github.com/Project60/sepa_dd/releases/tag/1.0.1rc2)?

**Comment by Detsieber** [comment]
Sorry, I cannot test it myself - this issue happened at FIfF, where I
have no remote access...

Björn should upgrade the version and test next week during FIfF's office
hours.




Am 22.01.2015 um 17:34 schrieb SYSTOPIA:
