### ISSUE TITLE
API Names: not good enough

### ISSUE THREAD

**Issue by tttp** [Project60/sepa_dd#33]
ok, I don't like the entity names anymore. To be clear: it's my fault, I didn't choose them right enough

$dao['SepaMandate'] = 'CRM_Sepa_DAO_SEPAMandate';
$dao['SepaCreditor'] = 'CRM_Sepa_DAO_SEPACreditor';
$dao['SepaSddFile'] = 'CRM_Sepa_DAO_SEPASddFile';

Why is DAO_SEPA instead of DAO? Sepa is already there in the name

$dao['SepaTransactionGroup'] = 'CRM_Sepa_DAO_SEPATransactionGroup';
$dao['SepaContributionGroup'] = 'CRM_Sepa_DAO_SEPAContributionGroup';

It confuses the hell out of me, TransactionGroup is a "group", ContributionGroup is a join table between contribution and group

what about

SepaTxGroup
SepaContribution

we don't change the structure, just the name so my wee brain won't get all twisted.

@pdelbar @systopia, comments before I break everything in the sprint?

**Comment by systopia** [comment]
6 months of no interest... I'll close it :)
